"""
Massive search query templates and word lists for traffic noise generation.
Each variable list targets 100+ entries minimum for high-variety output.
"""

QUERY_TEMPLATES = {
    "search": {
        "templates": [
            "best {product} {year}", "how to {fix_action} {household_item}",
            "{recipe_adj} {food} recipe", "{food} recipe for {occasion}",
            "weather in {city} this week", "best {product} under {price}",
            "{service} near me", "diy {home_project}", "how to {life_skill}",
            "best {product} for {use_case}", "{city} things to do this weekend",
            "how much does {service} cost", "{brand} vs {brand} review",
            "is {product} worth it {year}", "cheap {product} deals",
            "how to clean {household_item}", "best {food} restaurants in {city}",
            "{car_brand} {car_type} {year} review", "used {car_brand} for sale near me",
            "how to save money on {expense}", "{sport} scores today",
            "{streaming} best shows {year}", "when does {show} come out",
            "best books {genre} {year}", "how to lose weight {method}",
            "{exercise} workout for beginners", "best {supplement} for {health_goal}",
            "{home_project} cost estimate", "how to {cooking_method} {food}",
            "best {pet} breeds for {living_situation}", "{pet} {pet_issue} remedies",
            "how to get rid of {pest}", "{holiday} gift ideas {year}",
            "best {clothing} for {season}", "how to style {clothing}",
            "top 10 {product} {year}", "{product} black friday deals",
            "where to buy {product} cheap", "{brand} {product} warranty",
            "{city} real estate market {year}", "rent vs buy {city}",
            "best neighborhoods in {city}", "{city} weather forecast",
            "flights from {city} to {city}", "road trip from {city} to {city}",
            "best {food} delivery {city}", "happy hour near {city}",
            "{sport} schedule {year}", "{sport} draft picks {year}",
            "fantasy {sport} rankings {year}", "{sport} injuries today",
            "how to {hobby} for beginners", "best {hobby} equipment",
            "{hobby} classes near me", "{hobby} tips and tricks",
            "{college} acceptance rate {year}", "best {major} programs",
            "how to apply for {financial}", "{financial} requirements {year}",
            "best {phone_brand} phone {year}", "{phone_brand} vs {phone_brand}",
            "{software} tutorial for beginners", "how to use {software}",
            "best {software} alternatives free", "{software} pricing {year}",
            "{medical} symptoms", "when to see a doctor for {medical}",
            "home remedies for {medical}", "{medical} treatment options",
            "best {insurance} companies {year}", "cheapest {insurance} rates",
            "how to file {insurance} claim", "{insurance} quote online",
        ],
        "vars": {
            "product": [
                "wireless headphones", "laptop", "monitor", "keyboard", "mouse", "webcam",
                "air fryer", "vacuum cleaner", "mattress", "office chair", "standing desk",
                "smart watch", "tablet", "router", "dash cam", "security camera",
                "blender", "instant pot", "coffee maker", "air purifier", "dehumidifier",
                "electric toothbrush", "noise canceling earbuds", "portable charger",
                "gaming headset", "microphone", "ring light", "power strip",
                "lawn mower", "pressure washer", "drill", "tool set", "generator",
                "robot vacuum", "smart speaker", "fitness tracker", "e-reader",
                "projector", "soundbar", "external hard drive", "SSD", "NAS",
                "smart doorbell", "thermostat", "water filter", "espresso machine",
                "electric kettle", "toaster oven", "slow cooker", "rice cooker",
                "food processor", "stand mixer", "dishwasher", "washing machine",
                "dryer", "refrigerator", "chest freezer", "portable AC",
                "space heater", "humidifier", "steam mop", "carpet cleaner",
                "leaf blower", "chainsaw", "hedge trimmer", "snow blower",
                "power washer", "table saw", "compound miter saw", "angle grinder",
                "impact driver", "oscillating tool", "stud finder", "laser level",
                "bike helmet", "running watch", "yoga mat", "resistance bands",
                "dumbbell set", "pull up bar", "foam roller", "massage gun",
                "electric scooter", "hoverboard", "drone", "action camera",
                "VR headset", "gaming monitor", "mechanical keyboard", "gaming mouse",
                "stream deck", "capture card", "USB hub", "docking station",
                "ergonomic mouse", "monitor arm", "desk lamp", "blue light glasses",
                "noise machine", "weighted blanket", "pillow", "bed frame",
                "couch", "bookshelf", "desk", "filing cabinet",
                "backpack", "luggage", "travel pillow", "packing cubes",
            ],
            "year": ["2024", "2025", "2026"],
            "fix_action": [
                "fix", "repair", "replace", "install", "unclog", "patch", "adjust",
                "rewire", "reseal", "refinish", "repaint", "realign", "troubleshoot",
                "calibrate", "flush", "bleed", "tighten", "lubricate", "weatherstrip",
            ],
            "household_item": [
                "leaky faucet", "running toilet", "garbage disposal", "dishwasher",
                "dryer", "washing machine", "water heater", "thermostat", "smoke detector",
                "ceiling fan", "light switch", "door knob", "window screen", "gutter",
                "drywall hole", "squeaky door", "garage door opener", "sprinkler system",
                "kitchen sink", "bathroom tile", "shower head", "toilet flapper",
                "refrigerator ice maker", "oven igniter", "microwave turntable",
                "AC filter", "furnace pilot light", "sump pump", "water softener",
                "circuit breaker", "outlet", "dimmer switch", "doorbell",
                "fence post", "deck boards", "porch railing", "mailbox",
                "shingle", "downspout", "window seal", "door weatherstrip",
            ],
            "recipe_adj": [
                "easy", "quick", "healthy", "keto", "vegan", "gluten free",
                "slow cooker", "instant pot", "air fryer", "one pot", "30 minute",
                "budget", "meal prep", "high protein", "low carb", "mediterranean",
                "paleo", "whole30", "dairy free", "sugar free", "low sodium",
                "kid friendly", "freezer friendly", "no bake", "dump and go",
                "5 ingredient", "sheet pan", "one skillet", "cast iron",
                "grilled", "smoked", "sous vide", "fermented", "raw",
            ],
            "food": [
                "chicken", "salmon", "pasta", "tacos", "steak", "shrimp", "tofu",
                "rice bowl", "soup", "chili", "curry", "stir fry", "pizza dough",
                "banana bread", "pancakes", "smoothie", "meatloaf", "pulled pork",
                "mac and cheese", "fried rice", "ramen", "burrito bowl", "lasagna",
                "pot roast", "meatballs", "fried chicken", "fish tacos", "beef stew",
                "chicken wings", "ribs", "brisket", "pork chops", "lamb chops",
                "crab cakes", "lobster", "scallops", "sushi", "pho",
                "pad thai", "tikka masala", "butter chicken", "biryani",
                "falafel", "hummus", "guacamole", "salsa", "bruschetta",
                "quiche", "frittata", "omelette", "french toast", "waffles",
                "cookies", "brownies", "cheesecake", "tiramisu", "creme brulee",
                "sourdough bread", "focaccia", "naan", "cornbread", "biscuits",
                "potato soup", "tomato soup", "french onion soup", "clam chowder",
                "caesar salad", "cobb salad", "greek salad", "poke bowl",
            ],
            "occasion": [
                "dinner tonight", "meal prep", "date night", "family dinner",
                "super bowl party", "birthday party", "potluck", "camping", "kids",
                "thanksgiving", "christmas dinner", "easter brunch", "fourth of july",
                "game day", "tailgate", "baby shower", "wedding reception",
                "lunch box", "road trip", "picnic", "backyard bbq", "brunch",
                "weeknight", "sunday dinner", "holiday party", "new years eve",
            ],
            "city": [
                "Portland", "Austin", "Denver", "Seattle", "Nashville", "San Diego",
                "Miami", "Chicago", "Boston", "Atlanta", "Phoenix", "Las Vegas",
                "New York", "Los Angeles", "Houston", "Dallas", "Philadelphia",
                "San Francisco", "Detroit", "Minneapolis", "Charlotte", "Tampa",
                "Orlando", "San Antonio", "Jacksonville", "Columbus", "Indianapolis",
                "Raleigh", "Richmond", "Salt Lake City", "Kansas City", "Milwaukee",
                "New Orleans", "Pittsburgh", "Cincinnati", "Cleveland", "St Louis",
                "Sacramento", "Tucson", "Albuquerque", "Honolulu", "Anchorage",
                "Boise", "Burlington", "Savannah", "Charleston", "Asheville",
            ],
            "service": [
                "oil change", "dentist", "urgent care", "tire shop", "barber",
                "mechanic", "plumber", "electrician", "dog groomer", "dry cleaner",
                "gym", "yoga studio", "nail salon", "tattoo shop", "chiropractor",
                "eye doctor", "dermatologist", "therapist", "accountant", "lawyer",
                "vet", "pet sitter", "house cleaner", "landscaper", "handyman",
                "locksmith", "exterminator", "roofer", "HVAC repair", "carpet cleaning",
                "moving company", "storage unit", "notary public", "passport office",
                "DMV appointment", "car wash", "auto detailing", "towing",
            ],
            "home_project": [
                "bathroom remodel", "kitchen backsplash", "deck building",
                "fence installation", "painting interior walls", "installing shelves",
                "garden bed raised", "patio pavers", "closet organization",
                "basement finishing", "attic insulation", "crown molding",
                "hardwood floor install", "tile backsplash", "accent wall",
                "built in bookshelf", "mudroom bench", "garage storage",
                "outdoor kitchen", "fire pit", "pergola", "retaining wall",
                "french drain", "sump pump install", "egress window",
                "bathroom vanity", "kitchen island", "pantry shelving",
                "laundry room makeover", "home office setup", "nursery design",
            ],
            "life_skill": [
                "negotiate salary", "build credit", "file taxes",
                "change a tire", "jump start a car", "parallel park",
                "tie a tie", "iron a shirt", "sew a button",
                "write a resume", "ace a job interview", "meal prep for the week",
                "budget monthly", "invest in stocks", "start a 401k",
                "cook basic meals", "do laundry properly", "remove stains",
                "unclog a drain", "use a power drill", "hang curtains",
                "read a tape measure", "paint a room", "use jumper cables",
                "sharpen knives", "fold a fitted sheet", "organize a closet",
                "compost at home", "start seeds indoors", "prune bushes",
            ],
            "use_case": [
                "small apartment", "large family", "beginners", "seniors",
                "college students", "remote work", "travel", "outdoors", "gaming",
                "music production", "photography", "video editing", "streaming",
                "home gym", "meal prep", "camping", "backpacking", "fishing",
                "kids room", "dorm room", "RV", "tiny house", "garage",
            ],
            "brand": [
                "Samsung", "Apple", "Sony", "LG", "Nike", "Adidas",
                "Toyota", "Honda", "Tesla", "Dyson", "Ninja", "KitchenAid",
                "Dell", "HP", "Lenovo", "ASUS", "Bose", "JBL",
                "Anker", "Logitech", "Corsair", "Razer", "HyperX",
                "Vitamix", "Cuisinart", "Breville", "De'Longhi", "Keurig",
                "Weber", "Traeger", "DeWalt", "Milwaukee", "Makita",
                "Patagonia", "North Face", "Columbia", "Arc'teryx", "REI",
            ],
            "price": ["$25", "$50", "$100", "$200", "$300", "$500", "$1000", "$1500", "$2000"],
            "car_brand": [
                "Toyota", "Honda", "Ford", "Chevy", "Tesla", "Hyundai", "Kia",
                "BMW", "Subaru", "Mazda", "Nissan", "Volkswagen", "Audi",
                "Mercedes", "Lexus", "Acura", "Volvo", "Jeep", "Ram",
                "GMC", "Buick", "Cadillac", "Porsche", "Rivian", "Lucid",
            ],
            "car_type": ["SUV", "sedan", "truck", "hybrid", "electric", "minivan", "coupe", "convertible", "wagon", "crossover"],
            "expense": [
                "groceries", "gas", "insurance", "utilities", "rent", "internet",
                "phone bill", "subscriptions", "dining out", "clothing",
                "car payment", "student loans", "medical bills", "childcare",
                "pet expenses", "home maintenance", "transportation", "entertainment",
            ],
            "sport": [
                "NFL", "NBA", "MLB", "UFC", "soccer", "college basketball",
                "college football", "NHL", "MLS", "PGA", "tennis", "F1",
                "NASCAR", "boxing", "wrestling", "cricket", "rugby",
            ],
            "streaming": [
                "Netflix", "Hulu", "Disney Plus", "HBO Max", "Prime Video", "Peacock",
                "Paramount Plus", "Apple TV Plus", "Crunchyroll", "ESPN Plus",
                "YouTube TV", "Sling TV", "Fubo TV", "Discovery Plus",
            ],
            "show": [
                "Stranger Things season 5", "The Last of Us season 3", "House of the Dragon",
                "Yellowstone", "Wednesday season 2", "Squid Game season 3",
                "The Witcher season 4", "Cobra Kai season 7", "Ozark movie",
                "Bridgerton season 4", "The Bear season 4", "Severance season 3",
                "White Lotus season 3", "Andor season 2", "Daredevil Born Again",
                "The Mandalorian season 4", "Reacher season 3", "Fallout season 2",
                "3 Body Problem season 2", "Shogun season 2", "Rings of Power season 3",
            ],
            "genre": [
                "thriller", "romance", "sci fi", "fantasy", "self help", "biography",
                "mystery", "horror", "historical fiction", "true crime", "memoir",
                "business", "psychology", "philosophy", "poetry", "graphic novel",
                "young adult", "dystopian", "literary fiction", "adventure",
            ],
            "method": [
                "intermittent fasting", "walking", "without exercise", "naturally", "keto",
                "CICO", "weight watchers", "plant based diet", "low carb",
                "strength training", "running", "swimming", "yoga", "portion control",
            ],
            "exercise": [
                "ab", "arm", "leg", "full body", "HIIT", "yoga", "pilates", "cardio",
                "back", "chest", "shoulder", "glute", "core", "stretching",
                "kettlebell", "dumbbell", "bodyweight", "resistance band", "TRX",
            ],
            "supplement": [
                "protein powder", "creatine", "multivitamin", "fish oil", "pre workout",
                "collagen", "magnesium", "vitamin D", "zinc", "probiotics",
                "ashwagandha", "turmeric", "melatonin", "iron", "B12",
                "electrolytes", "BCAAs", "glutamine", "beta alanine", "citrulline",
            ],
            "health_goal": [
                "muscle gain", "energy", "sleep", "joint pain", "weight loss", "recovery",
                "immunity", "gut health", "skin health", "focus", "stress relief",
                "bone density", "heart health", "blood pressure", "inflammation",
            ],
            "cooking_method": [
                "grill", "smoke", "sous vide", "deep fry", "bake", "roast", "sear",
                "braise", "broil", "poach", "steam", "saute", "stir fry",
                "slow cook", "pressure cook", "air fry", "blacken", "flambe",
            ],
            "pet": ["dog", "cat", "fish", "hamster", "rabbit", "bird", "guinea pig", "turtle", "snake", "lizard", "ferret"],
            "pet_issue": [
                "anxiety", "shedding", "bad breath", "fleas", "itching", "not eating",
                "limping", "vomiting", "diarrhea", "aggression", "barking",
                "scratching furniture", "peeing inside", "separation anxiety",
            ],
            "living_situation": [
                "apartments", "families with kids", "first time owners", "active people",
                "seniors", "allergy sufferers", "small spaces", "cold climates",
                "hot climates", "single person", "couples", "rural areas",
            ],
            "pest": [
                "ants", "mice", "roaches", "fruit flies", "mosquitoes", "wasps", "termites",
                "bed bugs", "spiders", "rats", "gnats", "fleas", "ticks",
                "carpenter ants", "silverfish", "centipedes", "stink bugs", "moths",
            ],
            "holiday": [
                "Christmas", "birthday", "anniversary", "valentines day", "mothers day",
                "fathers day", "graduation", "wedding", "baby shower", "housewarming",
                "retirement", "easter", "halloween", "thanksgiving", "new years",
            ],
            "clothing": [
                "jeans", "sneakers", "dress shirt", "winter jacket", "swim trunks", "boots",
                "hoodie", "joggers", "polo shirt", "blazer", "chinos", "cargo pants",
                "rain jacket", "puffer vest", "flannel shirt", "henley", "peacoat",
                "oxford shoes", "loafers", "sandals", "work boots", "running shoes",
                "baseball cap", "beanie", "sunglasses", "watch", "belt", "backpack",
            ],
            "season": ["summer", "winter", "spring", "fall"],
            "hobby": [
                "photography", "woodworking", "gardening", "painting", "fishing",
                "hiking", "rock climbing", "kayaking", "surfing", "skateboarding",
                "cooking", "baking", "knitting", "pottery", "calligraphy",
                "3D printing", "drone flying", "astronomy", "bird watching",
                "archery", "golf", "tennis", "pickleball", "bowling",
                "chess", "piano", "guitar", "singing", "drawing",
                "journaling", "meditation", "leather working", "candle making",
            ],
            "college": [
                "MIT", "Stanford", "Harvard", "Yale", "Princeton", "Columbia",
                "UCLA", "Berkeley", "Michigan", "UVA", "Georgia Tech",
                "UT Austin", "Purdue", "Penn State", "Ohio State", "Florida",
            ],
            "major": [
                "computer science", "engineering", "nursing", "business",
                "psychology", "biology", "data science", "cybersecurity",
                "education", "communications", "accounting", "marketing",
            ],
            "financial": [
                "FAFSA", "student loan forgiveness", "mortgage", "personal loan",
                "credit card", "auto loan", "home equity line", "small business loan",
                "disability benefits", "social security", "unemployment",
            ],
            "phone_brand": [
                "iPhone", "Samsung Galaxy", "Google Pixel", "OnePlus", "Motorola",
                "Nothing Phone", "Sony Xperia", "Xiaomi",
            ],
            "software": [
                "Excel", "Photoshop", "AutoCAD", "Blender", "Python",
                "ChatGPT", "Notion", "Figma", "VS Code", "Docker",
                "Kubernetes", "Terraform", "Ansible", "Git", "Linux",
            ],
            "medical": [
                "headache", "back pain", "knee pain", "sore throat", "cough",
                "acid reflux", "insomnia", "anxiety", "allergies", "rash",
                "UTI", "ear infection", "pink eye", "shin splints", "plantar fasciitis",
                "carpal tunnel", "sciatica", "vertigo", "high blood pressure",
            ],
            "insurance": [
                "car", "home", "health", "life", "renters", "pet",
                "dental", "vision", "umbrella", "motorcycle", "travel",
            ],
        },
    },
    "adult_search": {
        "templates": [
            "best {adj} porn", "{category} videos", "{category} {adj}",
            "pornhub {category}", "xvideos {category} {adj}",
            "{ethnicity} {category}", "{body_type} {category}",
            "best {platform} creators {year}", "top {platform} accounts",
            "{position} tutorial", "how to {sex_skill}",
            "best {toy} for {gender}", "{toy} review {year}",
            "{kink} for beginners", "how to try {kink} safely",
            "{relationship} dating advice", "{relationship} relationship tips",
            "best {dating_app} tips", "{dating_app} vs {dating_app}",
            "how to {dating_action}", "{gender} {dating_action} tips",
            "{adj} {gender} onlyfans", "free {category} videos",
            "{body_part} {adj}", "big {body_part} {category}",
            "amateur {category} {ethnicity}", "homemade {category}",
            "{orientation} {category} videos", "{orientation} porn best",
            "{orientation} dating apps", "{orientation} bars near me",
            "trans {category}", "transgender {dating_action}",
            "ftm dating advice", "mtf passing tips",
            "nonbinary {category}", "genderfluid fashion",
            "drag queen {city} shows", "pride events {city} {year}",
            "queer friendly {service} near me", "lgbtq therapist near me",
            "coming out as {orientation}", "how to support {orientation} partner",
            "{orientation} romance books", "{orientation} movies {year}",
            "{body_type} {ethnicity} {category}", "{adj} {category} {ethnicity}",
            "best {category} subreddits", "reddit {category} {adj}",
            "{category} onlyfans leaked", "{platform} free trial",
            "how to last longer during {position}", "{position} for {body_type} people",
            "{ethnicity} {gender} {platform}", "best {adj} {category} sites",
            "{kink} gear for beginners", "best {kink} toys",
            "{orientation} {kink} community", "{orientation} {category} {adj}",
            "{body_type} {orientation} dating", "{age_group} dating tips",
            "how to find {relationship} partner", "{relationship} rules and boundaries",
            "best {lingerie} for {body_type}", "{lingerie} shopping guide",
        ],
        "vars": {
            "adj": [
                "hot", "best", "top rated", "new", "trending", "popular", "amateur",
                "professional", "HD", "homemade", "real", "passionate", "rough",
                "sensual", "romantic", "intense", "wild", "gentle", "hardcore", "soft",
                "exclusive", "premium", "free", "full length", "uncensored",
                "vintage", "classic", "taboo", "forbidden", "naughty",
            ],
            "category": [
                "milf", "teen 18+", "mature", "couple", "threesome", "solo",
                "lesbian", "gay", "bisexual", "trans", "interracial", "latina",
                "asian", "ebony", "blonde", "brunette", "redhead", "BBW",
                "petite", "curvy", "muscular", "tattooed", "pierced",
                "massage", "stepmom", "stepsister", "teacher", "nurse",
                "cosplay", "outdoor", "shower", "pool", "public",
                "anal", "oral", "creampie", "squirt", "bondage",
                "roleplay", "POV", "gangbang", "orgy", "swingers",
                "compilation", "casting", "behind the scenes", "bloopers",
                "double penetration", "fisting", "foot fetish", "face sitting",
                "deepthroat", "handjob", "titjob", "rimming", "pegging",
                "glory hole", "bukkake", "facial", "cumshot", "money shot",
                "girl on girl", "boy on boy", "MMF", "FFM", "group",
                "voyeur", "exhibitionist", "caught", "hidden camera",
                "yoga", "gym", "office", "car", "hotel", "beach",
                "college", "party", "club", "festival", "vacation",
            ],
            "ethnicity": [
                "latina", "ebony", "asian", "indian", "middle eastern",
                "european", "japanese", "korean", "filipina", "brazilian",
                "colombian", "mexican", "african", "caribbean", "mixed race",
                "white", "black", "arab", "persian", "thai",
                "vietnamese", "chinese", "indonesian", "italian", "french",
                "spanish", "german", "british", "russian", "polish",
                "puerto rican", "dominican", "cuban", "hawaiian", "native american",
                "australian", "scandinavian", "irish", "scottish", "turkish",
            ],
            "body_type": [
                "petite", "curvy", "thick", "slim", "athletic", "BBW",
                "fit", "muscular", "tall", "short", "voluptuous", "skinny",
                "plus size", "hourglass", "pear shaped", "busty", "flat chested",
                "toned", "chubby", "average", "stocky", "lean",
                "thicc", "juicy", "stacked", "tiny", "amazon",
                "dad bod", "bear", "twink", "otter", "jock", "cub",
            ],
            "body_part": [
                "boobs", "ass", "dick", "tits", "butt", "cock",
                "breasts", "thighs", "abs", "feet", "legs",
                "nipples", "pussy", "vagina", "penis", "balls",
                "chest", "back", "neck", "lips", "hands",
                "tongue", "hips", "waist", "calves", "biceps",
            ],
            "position": [
                "missionary", "doggy style", "cowgirl", "reverse cowgirl",
                "69", "spooning", "standing", "prone bone", "lotus",
                "wheelbarrow", "pretzel", "butterfly", "amazon",
                "pile driver", "seated", "against the wall", "on the table",
                "shower sex", "lazy dog", "the bridge", "the spider",
                "face to face", "from behind", "on top", "underneath",
                "side by side", "kneeling", "suspended", "inverted",
            ],
            "sex_skill": [
                "last longer in bed", "give better head",
                "find the g spot", "have multiple orgasms",
                "be better at foreplay", "talk dirty", "use handcuffs safely",
                "introduce toys in bedroom", "have anal sex safely",
                "improve stamina", "give a prostate massage",
                "eat pussy", "give a blowjob", "edge properly",
                "squirt", "deepthroat without gagging", "give a lap dance",
                "role play ideas", "set the mood", "have phone sex",
                "sext properly", "take better nudes", "use a vibrator",
                "have tantric sex", "master kegel exercises",
                "communicate desires", "recover from bad sex",
                "have sex in public safely", "use lube properly",
            ],
            "toy": [
                "vibrator", "dildo", "butt plug", "cock ring", "fleshlight",
                "strap on", "prostate massager", "wand massager", "nipple clamps",
                "bondage kit", "sex swing", "remote vibrator", "suction toy",
                "rabbit vibrator", "bullet vibrator", "g spot vibrator",
                "anal beads", "double ended dildo", "realistic dildo",
                "penis pump", "chastity cage", "spreader bar", "blindfold",
                "feather tickler", "paddle", "flogger", "riding crop",
                "love egg", "kegel balls", "penis sleeve", "masturbator",
            ],
            "gender": [
                "women", "men", "couples", "him", "her", "nonbinary people",
                "trans women", "trans men", "femme", "masc", "androgynous",
                "genderqueer", "genderfluid", "agender", "two spirit",
            ],
            "kink": [
                "BDSM", "bondage", "role play", "foot fetish", "domination",
                "submission", "edging", "pegging", "cuckolding", "voyeurism",
                "exhibitionism", "sensory deprivation", "wax play", "spanking",
                "choking", "double penetration", "group sex", "swinging",
                "age play", "pet play", "rope bondage", "shibari",
                "impact play", "knife play", "temperature play", "electro play",
                "breath play", "degradation", "praise kink", "breeding kink",
                "size kink", "uniform kink", "latex", "leather",
                "lingerie fetish", "stocking fetish", "pantyhose fetish",
                "muscle worship", "armpit fetish", "belly button fetish",
            ],
            "relationship": [
                "open relationship", "polyamorous", "monogamous",
                "long distance", "friends with benefits", "casual",
                "dom sub", "sugar daddy", "cougar", "age gap",
                "throuple", "swinger lifestyle", "hotwife",
                "relationship anarchy", "monogamish", "solo poly",
                "nesting partner", "metamour", "compersion",
            ],
            "dating_app": [
                "Tinder", "Bumble", "Hinge", "Grindr", "Her",
                "Feeld", "OkCupid", "Scruff", "Taimi", "3Fun",
                "Lex", "HER", "Zoosk", "Match", "eHarmony",
                "Coffee Meets Bagel", "Plenty of Fish", "Happn",
                "Thursday", "Raya", "The League", "Snack",
            ],
            "dating_action": [
                "flirt", "sext", "send nudes safely",
                "have a one night stand", "find a hookup",
                "ask someone out", "recover from rejection",
                "write a bio", "take good dating photos",
                "make the first move", "plan a first date",
                "kiss on the first date", "know if they like you",
                "deal with ghosting", "end things respectfully",
                "transition from dating to relationship",
                "bring up exclusivity", "navigate situationships",
            ],
            "platform": [
                "OnlyFans", "Fansly", "Pornhub", "Chaturbate", "ManyVids",
                "Stripchat", "LiveJasmin", "CamSoda", "MyFreeCams",
                "BongaCams", "Flirt4Free", "ImLive", "Streamate",
                "Clips4Sale", "iWantClips", "LoyalFans", "FanCentro",
            ],
            "orientation": [
                "gay", "lesbian", "bisexual", "pansexual", "queer",
                "asexual", "demisexual", "heteroflexible", "bicurious", "straight",
                "omnisexual", "polysexual", "graysexual", "sapiosexual",
                "aromantic", "biromantic", "panromantic", "questioning",
            ],
            "city": [
                "NYC", "LA", "San Francisco", "Miami", "Chicago",
                "Atlanta", "Portland", "Austin", "New Orleans", "Seattle",
                "Denver", "Nashville", "Las Vegas", "Houston", "Dallas",
                "Philadelphia", "Boston", "Minneapolis", "San Diego", "Phoenix",
                "Detroit", "DC", "Tampa", "Orlando", "Charlotte",
            ],
            "service": [
                "doctor", "therapist", "gym", "bar", "church",
                "community center", "bookstore", "cafe", "salon",
                "spa", "yoga studio", "dance studio", "support group",
                "counselor", "wedding planner", "photographer",
            ],
            "year": ["2024", "2025", "2026"],
            "age_group": [
                "over 30", "over 40", "over 50", "over 60",
                "in your 20s", "in your 30s", "in your 40s",
                "after divorce", "as a single parent", "after coming out",
            ],
            "lingerie": [
                "lingerie", "bra", "panties", "thong", "corset", "bodysuit",
                "babydoll", "teddy", "chemise", "garter belt", "stockings",
                "bralette", "crotchless panties", "harness", "robe",
            ],
        },
    },
}
