---
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
